version: "3.7"
services:
  db:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_DB: discogs
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
    ports:
      - 5432:5432
    volumes:
      - ./dbdata:/var/lib/postgresql/data

#  decoder:
#    image: golang:1.13.5-alpine
#    environment:
#      DB_HOST: db
#      DB_PORT: 5432
#      DB_SSL_MODE: disabled
#      DB_NAME: discogs
#      DB_USERNAME: user
#      DB_PASSWORD: password
#      FILE_NAME: /source/discogs_20191101_artists.xml
#      FILE_TYPE: artists
#      BLOCK_SIZE: 10000
#      BLOCK_SKIP: 0
#      BLOCK_LIMIT: 2147483647
#    volumes:
#      - ./source:/source