version: "3.7"
services:
  db:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_DB: discogs
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
    ports:
      - 5432:5432
    volumes:
      - ./dbdata:/var/lib/postgresql/data